### ISSUE TITLE
How to destroy and/or reload warpdrive

### ISSUE THREAD

**Issue by westonganger** [NiklasKnaack/jquery-warpdrive-plugin#2]
Getting major memory leaks when trying to remove the canvas and create a new one when settings change. Do you know of a way to solve or workaround this?

**Comment by NiklasKnaack** [comment]
Thanks for the hint. So far this plugin did not have such a method. For this reason I have added a new method called destroy. Have a look at the updated README.md, which explains how to use the new method. Let me know if it works now.

**Comment by westonganger** [comment]
Great! The implementation looks fantastic. You sir are a gentleman and scholar. 

This is good enough for me or could there a better way to reload the canvas with new settings, rather than destroy/re-init?

**Comment by NiklasKnaack** [comment]
Counter question: What exactly are you planning to do? Is there an example to look at?
Without further information I would say destroy/re-init is the right choice.

**Comment by westonganger** [comment]
Im really just experimenting because this plugin is pretty cool but one use case is that I want to toggle Mouse/Touch. However really it could be any change of settings. 

What I was thinking was to re-use somehow the existing canvas instead of destroying the element completely and creating a new one from scratch. My uneducated idea could be something as simple as clearing the canvas and re-drawing it or maybe there's something better without down the rabbit-hole too much.

**Comment by NiklasKnaack** [comment]
With some of the settings lookup tables are created. Therefore it is not possible to change some of the settings while running. 
For example, to toggle between mouse/touch you would have to add a corresponding method. That would be quite simple.
I'm assuming this issue is resolved, so I'll close it soon.

**Comment by westonganger** [comment]
Ok sounds good. Thank you very much for adding the `destroy` method. Closing.
